### ISSUE TITLE
i don't know err  ,is why?

### ISSUE THREAD

**Issue by anwerteq** [csfloat/inspect#183]
Debugger attached.
Waiting for the debugger to disconnect...
C:\Users\QingLiu\Desktop\temp111\csgofloat-inspect-api\node_modules\pg-pool\index.js:45
    Error.captureStackTrace(err);
          ^
error: 语法错误 在 "NOT" 或附近的
    at C:\Users\QingLiu\Desktop\temp111\csgofloat-inspect-api\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Postgres.ensureSchema (C:\Users\QingLiu\Desktop\temp111\csgofloat-inspect-api\lib\postgres.js:56:9) {
  length: 94,
  severity: '错误',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '1029',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1006',
  routine: 'scanner_yyerror'
}

**Comment by anwerteq** [comment]
can you help me

**Comment by anwerteq** [comment]
i use pg version is 9.2.24
