### ISSUE TITLE
this.debug is not a function

### ISSUE THREAD

**Issue by vladdnepr** [csfloat/inspect#187]
Hi.

Today at midnight I received lot of errors AccountLoginDeniedThrottle. I use lot of proxies. Also received this error locally too. 

I tried to login with login/pass and 2fa code via official client and all works fine.

Also sometimes I got 

```
TypeError: this.debug is not a function
2023-09-13 11:17:11     at LoginSession.<anonymous> (/usr/src/csgofloat/node_modules/steam-user/components/09-logon.js:377:10)
2023-09-13 11:17:11     at LoginSession.emit (node:events:513:28)
2023-09-13 11:17:11     at LoginSession._doPoll (/usr/src/csgofloat/node_modules/steam-session/dist/LoginSession.js:274:18)
```

After I replaced this.debug with console.log I received

```
2023-09-13 11:27:36 Error: FileNotFound
2023-09-13 11:27:36     at eresultError (/usr/src/csgofloat/node_modules/steam-session/dist/helpers.js:17:15)
2023-09-13 11:27:36     at AuthenticationClient.sendRequest (/usr/src/csgofloat/node_modules/steam-session/dist/AuthenticationClient.js:213:46)
2023-09-13 11:27:36     at async AuthenticationClient.pollLoginStatus (/usr/src/csgofloat/node_modules/steam-session/dist/AuthenticationClient.js:129:22)
2023-09-13 11:27:36     at async LoginSession._doPoll (/usr/src/csgofloat/node_modules/steam-session/dist/LoginSession.js:270:28) {
2023-09-13 11:27:36   eresult: 9
2023-09-13 11:27:36 }
```

https://steamerrors.com/9

I don't know what happened with csgofloat inspect or steam today, but maybe someone know something?

**Comment by pcheloveker** [comment]
I have the same problem.
The error we should have seen 09-login.js:377:
> steam-session error: FileNotFound

My log also contains:
```
error: Failed to fetch items_game.txt
error: Failed to fetch csgo_english.txt
error: Failed to fetch items_game_cdn.txt
```

Url:

> https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/scripts/items/items_game.txt
404 not found

SteamDatabase/GameTracking-CSGO -> SteamDatabase/GameTracking-CS2 and does not contain items_game.txt and items_game_cdn.txt

**Comment by aavvaavvaa** [comment]
@vladdnepr You have to update node steam-user dependency of your project

**Comment by aavvaavvaa** [comment]
Open terminal got to your project folder and type `npm update`

**Comment by FXXDEV** [comment]
Im with this problem and have update the project folder/steam-user as @aavvaavvaa told about above 

```
 message=AccountLoginDeniedThrottle, stack=Error: AccountLoginDeniedThrottle
    at SteamUser._handleLogOnResponse 
```
`node_modules\steam-user\components\09-logon.js:400:10, eresult=87`

**Comment by FXXDEV** [comment]
Im stuck with the problem

Someone can help me? 


Update does not work for me

**Comment by vladdnepr** [comment]
I use proxies. Are you?

**Comment by aavvaavvaa** [comment]
@FXXDEV It's not a steam-user library problem, it is an account problem, valve's system thinks that you are trying to break into account https://steamerrors.com/87

**Comment by s1ssl0** [comment]
> Im stuck with the problem
> 
> Someone can help me?
> 
> Update does not work for me

You'll have to deactivate steam guard in the steam accounts settings. I've done it manually because i dont have many bots, but if will write a script share it.

**Comment by CAKyPA** [comment]
```
How to First Login a Bot
Note: If the bot has never logged into the steam client before and doesn't have Mobile 2FA enabled (fresh account), you can just input the username and password and it should successfully log in without email 2FA
```
Not related to the issue, but is steam requiring 2FA codes for fresh accounts now?
